import {
  DeliveryDiningOutlined,
  Discount,
  MessageOutlined,
  Payment,
} from "@mui/icons-material";

export const products = [
  {
    id: 1,
    title: "Shiny Dress",
    stars: 2,
    reviews: 4.1,
    brand: "chanel",
    description: "Adidas samba for casual wear",
    price: 95.5,
    category: ["women", "shoes", "soft", "women's fashion"],
    colors: ["black", "blue", "green", "white"],
    size: ["S", "M", "L", "XL"],
    img: "../assets/Images.png",
  },
  {
    id: 2,
    title: "Long dress",
    stars: 4,
    reviews: 4.1,
    brand: "chanel",
    description: "SB for casual wear",
    price: 650,
    category: ["women", "dress", "casual", "women's fashion"],
    colors: ["black", "green", "white"],
    size: ["S", "M", "L", "XL"],
    img: "../assets/Images-1.png",
  },
  {
    id: 3,
    title: "Pijamas",
    stars: 3,
    reviews: 4.1,
    brand: "chanel",
    description: "New balance 530 for casual wear and modern look",
    price: 400,
    category: ["women", "dress"],
    colors: ["black", "white"],
    size: ["S", "M", "L", "XL"],
    img: "../assets/Images-2.png",
  },
  {
    id: 4,
    title: "NEW BALANCE 530",
    stars: 2,
    reviews: 4.1,
    brand: "chanel",
    description: "New balance 530 for casual wear and modern look",
    price: 400,
    category: ["women", "dress"],
    colors: ["black", "white"],
    size: ["S", "M", "L", "XL"],
    img: "../assets/Images-3.png",
  },
  {
    id: 5,
    title: "Sunglases",
    stars: 3,
    reviews: 4.1,
    brand: "chanel",
    description: "New balance 530 for casual wear and modern look",
    price: 400,
    category: ["women", "dress", "women's accessorie"],
    colors: ["black", "white"],
    size: ["S", "M", "L", "XL"],
    img: "../assets/Images-4.png",
  },
  {
    id: 6,
    title: "NEW BALANCE 530",
    stars: 4,
    reviews: 4.1,
    brand: "chanel",
    description: "New balance 530 for casual wear and modern look",
    price: 400,
    category: ["women", "dress"],
    colors: ["black", "white"],
    size: ["S", "M", "L", "XL"],
    img: "../assets/Images-5.png",
  },
];

// export const offers = [
//   {
//     id: 1,
//     title: "Fast delivery",
//     description: "Free Shipping for orders over £130",
//     icon: <DeliveryDiningOutlined />,
//   },
//   {
//     id: 2,
//     title: "Secure SSL",
//     description: "256-Bit Payment Protection",
//     icon: <MessageOutlined />,
//   },
//   {
//     id: 3,
//     title: "Paypal Or appDelivery",
//     description: "Pay with multiple credit cards",
//     icon: <Payment />,
//   },
//   {
//     id: 4,
//     title: "Get discounts",
//     description: "Join the sale campaign",
//     icon: <Discount />,
//   },
// ];
